//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingdee.CAPP.UI.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kingdee.CAPP.UI.Resource.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 新增文件夹 的本地化字符串。
        /// </summary>
        internal static string AddNewFolder {
            get {
                return ResourceManager.GetString("AddNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增模版 的本地化字符串。
        /// </summary>
        internal static string AddNewModule {
            get {
                return ResourceManager.GetString("AddNewModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还没有填写工艺规程的名称！ 的本地化字符串。
        /// </summary>
        internal static string HAVENOTFILLPROCESSPLANNINGNAME {
            get {
                return ResourceManager.GetString("HAVENOTFILLPROCESSPLANNINGNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还没有选择卡片模板！ 的本地化字符串。
        /// </summary>
        internal static string HAVENOTSELECTEDCARDMODULE {
            get {
                return ResourceManager.GetString("HAVENOTSELECTEDCARDMODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动自动升级检查程序失败！ 的本地化字符串。
        /// </summary>
        internal static string LANCHAUTOUPGRADEFAILED {
            get {
                return ResourceManager.GetString("LANCHAUTOUPGRADEFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前用户没有权限操作注册表！ 的本地化字符串。
        /// </summary>
        internal static string NOTHAVERIGHTOPERATIONREGISTRY {
            get {
                return ResourceManager.GetString("NOTHAVERIGHTOPERATIONREGISTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户密码错误！ 的本地化字符串。
        /// </summary>
        internal static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入密码！ 的本地化字符串。
        /// </summary>
        internal static string PasswordIsEmpty {
            get {
                return ResourceManager.GetString("PasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10,25,40,55,70,85,100,115,130,145,160,175,190,205,220,235,250,265,280,295,310,325,340,355,370,385,400 的本地化字符串。
        /// </summary>
        internal static string PercentNum {
            get {
                return ResourceManager.GetString("PercentNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System.Windows.Forms.AxHost+State 的本地化字符串。
        /// </summary>
        internal static string player_OcxState {
            get {
                return ResourceManager.GetString("player.OcxState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺规程 的本地化字符串。
        /// </summary>
        internal static string PROCESSPROCEDUREROOT {
            get {
                return ResourceManager.GetString("PROCESSPROCEDUREROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册AutoCAD插件失败！ 的本地化字符串。
        /// </summary>
        internal static string REGESIGERAUTOCADPLUGINFAIL {
            get {
                return ResourceManager.GetString("REGESIGERAUTOCADPLUGINFAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新程序已启动！ 的本地化字符串。
        /// </summary>
        internal static string UPGRADEAPPALREADYRUN {
            get {
                return ResourceManager.GetString("UPGRADEAPPALREADYRUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入用户名！ 的本地化字符串。
        /// </summary>
        internal static string UserNameIsEmpty {
            get {
                return ResourceManager.GetString("UserNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在！ 的本地化字符串。
        /// </summary>
        internal static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或密码不正确！ 的本地化字符串。
        /// </summary>
        internal static string UserORPasswordError {
            get {
                return ResourceManager.GetString("UserORPasswordError", resourceCulture);
            }
        }
    }
}
