//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingdee.CAPP.Solidworks.RoutingPlugIn {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kingdee.CAPP.Solidworks.RoutingPlugIn.UIResource", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增工艺文件失败，错误原因如下：.
        /// </summary>
        internal static string NEWADDPROCESSFAILURE {
            get {
                return ResourceManager.GetString("NEWADDPROCESSFAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增工艺时必须先选择工艺路线！.
        /// </summary>
        internal static string NEWADDPROCESSPLEASECHOICEROUTING {
            get {
                return ResourceManager.GetString("NEWADDPROCESSPLEASECHOICEROUTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增工艺文件成功！.
        /// </summary>
        internal static string NEWADDPROCESSSUCESS {
            get {
                return ResourceManager.GetString("NEWADDPROCESSSUCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增工艺路线失败，错误原因如下：.
        /// </summary>
        internal static string NEWADDROUTINGFAILURE {
            get {
                return ResourceManager.GetString("NEWADDROUTINGFAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增工艺路线成功！.
        /// </summary>
        internal static string NEWADDROUTINGSUCESS {
            get {
                return ResourceManager.GetString("NEWADDROUTINGSUCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择零件文件！.
        /// </summary>
        internal static string PLEASESELECTPARTFILE {
            get {
                return ResourceManager.GetString("PLEASESELECTPARTFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工序代码不能为空！.
        /// </summary>
        internal static string PROCESSCODECANOTNULL {
            get {
                return ResourceManager.GetString("PROCESSCODECANOTNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工序名称不能为空！.
        /// </summary>
        internal static string PROCESSNAMECANOTNULL {
            get {
                return ResourceManager.GetString("PROCESSNAMECANOTNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工艺路线代码不能为空！.
        /// </summary>
        internal static string ROUTINGCODECANOTNULL {
            get {
                return ResourceManager.GetString("ROUTINGCODECANOTNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工艺路线名称不能为空,.
        /// </summary>
        internal static string ROUTINGNAMECANOTNULL {
            get {
                return ResourceManager.GetString("ROUTINGNAMECANOTNULL", resourceCulture);
            }
        }
    }
}
