//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingdee.CAPP.UpgradeClient.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kingdee.CAPP.UpgradeClient.Resource.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 自动更新 的本地化字符串。
        /// </summary>
        internal static string AUTOUPGRADE {
            get {
                return ResourceManager.GetString("AUTOUPGRADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到应用程序进程:{0},如果当前应用程序正在运行,请手动关闭它！ 的本地化字符串。
        /// </summary>
        internal static string CANNOTFINDAPPLICATIONPROCESS {
            get {
                return ResourceManager.GetString("CANNOTFINDAPPLICATIONPROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到远程的更新文件:Upgrade.xml！ 的本地化字符串。
        /// </summary>
        internal static string CANNOTFINDREMOTEUPGRADEFILE {
            get {
                return ResourceManager.GetString("CANNOTFINDREMOTEUPGRADEFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在检查应用程序更新，请稍后... 的本地化字符串。
        /// </summary>
        internal static string CHECKINGUPGRADE {
            get {
                return ResourceManager.GetString("CHECKINGUPGRADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭应用程序进程:{0}失败,请手动关闭当前应用程序！ 的本地化字符串。
        /// </summary>
        internal static string CLOSEAPPLICATIONPROCESSFAILED {
            get {
                return ResourceManager.GetString("CLOSEAPPLICATIONPROCESSFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前已经是最新版本！ 的本地化字符串。
        /// </summary>
        internal static string CURRENTISLASTLYVERSON {
            get {
                return ResourceManager.GetString("CURRENTISLASTLYVERSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载完成！ 的本地化字符串。
        /// </summary>
        internal static string DOWNLOADCOMPLETE {
            get {
                return ResourceManager.GetString("DOWNLOADCOMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载文件，请不要关闭窗口！ 的本地化字符串。
        /// </summary>
        internal static string DOWNLOADINGFILE {
            get {
                return ResourceManager.GetString("DOWNLOADINGFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载或更新文件:{0}时出现以下异常\r\n{0}下载更新文件！ 的本地化字符串。
        /// </summary>
        internal static string DOWNLOADUPGRADEFILEERROR {
            get {
                return ResourceManager.GetString("DOWNLOADUPGRADEFILEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在安装升级文件！ 的本地化字符串。
        /// </summary>
        internal static string INSTALLINGUPGRADEFILE {
            get {
                return ResourceManager.GetString("INSTALLINGUPGRADEFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动程序：{0}失败,请手动启动！ 的本地化字符串。
        /// </summary>
        internal static string STARTUPAPPLICATIONFAILED {
            get {
                return ResourceManager.GetString("STARTUPAPPLICATIONFAILED", resourceCulture);
            }
        }
    }
}
